# <font color='turquoise'>**NEURAL NETWORKS**</font>

**Neural networks** are a category of machine learning models inspired by the human brain. They are designed to recognize patterns and interpret sensory data through a kind of machine perception, labeling or clustering raw input.

A neural network takes in inputs, which are then processed in hidden layers using weights that are adjusted during training. Then the model spits out a prediction. The weights are adjusted to find patterns in order to make better predictions.

The network consists of layers. Each layer has multiple neurons (also called nodes). The layers are categorized into three types:

1. **Input Layer:** This layer receives all the inputs and forwards them to the hidden layer for analysis. Each node in the input layer represents one feature.

2. **Hidden Layer(s):** These are layers between the input and output layers. The magic of neural networks happens here, through the weights and activation functions. There can be multiple hidden layers in a network.

3. **Output Layer:** This layer receives inputs from the last hidden layer and transforms them into the format suitable for the problem at hand (e.g., for a binary classification problem, it would output a probability score near 0 or 1).

The power of neural networks comes from their ability to learn complex patterns and relationships from data, making them highly valuable for tasks like image and speech recognition, natural language processing, and other complex tasks.

## <font color='sky blue'>**Activation Functions**</font>

Activation functions are used in neural networks to introduce non-linearity into the network, allowing it to learn from complex data. Here are some common activation functions:

1. **Sigmoid Function:** The Sigmoid function is a smooth, S-shaped function that maps any real-valued number to a value between 0 and 1. It's often used in the output layer of a binary classification network.

    ```python
    def sigmoid(x):
        return 1 / (1 + np.exp(-x))
    ```

2. **Tanh (Hyperbolic Tangent) Function:** The tanh function is similar to the sigmoid function but maps any real-valued number to a value between -1 and 1. It's often used in hidden layers of a neural network.

    ```python
    def tanh(x):
        return np.tanh(x)
    ```

3. **ReLU (Rectified Linear Unit) Function:** The ReLU function outputs the input directly if it's positive; otherwise, it outputs zero. It's often used in hidden layers of a neural network.

    ```python
    def relu(x):
        return np.maximum(0, x)
    ```

4. **Leaky ReLU Function:** The Leaky ReLU function is a variant of ReLU that allows small negative values when the input is less than zero. It's used to fix the "dying ReLU" problem where a neuron might always output a negative value and therefore cannot make any progress since the gradient of ReLU is zero for negative inputs.

    ```python
    def leaky_relu(x):
        return np.maximum(0.01 * x, x)
    ```

5. **Softmax Function:** The Softmax function is often used in the output layer of a neural network for multi-class classification problems. It converts a vector of numbers into a vector of probabilities, where the probabilities of each value are proportional to the relative scale of each value in the vector.

    ```python
    def softmax(x):
        e_x = np.exp(x - np.max(x))
        return e_x / e_x.sum(axis=0)
    ```

Each of these activation functions has its own use cases and characteristics, and the choice of activation function can significantly impact the performance of a neural network.

## <font color='sky blue'>**Perceptron: a signle neuron with one layer**</font>

A single neuron with one layer is the simplest form of a neural network.

1. **Input:** The neuron receives one or more inputs. Each input comes with an associated weight which can be adjusted during the learning process. The weight increases the importance of the input if it's positive, or diminishes it if it's negative.

2. **Weighted Sum:** The neuron calculates the weighted sum of the inputs. This is done by multiplying each input by its corresponding weight and then adding them together.

3. **Add Bias:** The neuron then adds a bias term. The bias allows the neuron to shift the activation function to the left or right, which can be critical for successful learning.

4. **Activation Function:** The result of the weighted sum plus the bias is then passed through an activation function. The activation function introduces non-linearity into the output of a neuron. This non-linearity allows neural networks to learn from error and make adjustments, and it's what allows the network to model complex patterns.

5. **Output:** The result of the activation function is the final output of the neuron.




In [1]:
import pandas as pd
import numpy as np

In [33]:
#The training data, X are features and Y are the labels 
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
Y = np.array([[0, 0, 1, 1]]).T
print(Y)


[[0]
 [0]
 [1]
 [1]]


In [34]:
def sigmoid(x, deriv=False):
    if deriv == True:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

In [35]:
#Initializing the weights to random small values
W = 2 * np.random.random((3, 1)) - 1
print(W)

[[ 0.49737296]
 [ 0.55432718]
 [-0.65129331]]


In [41]:
#The alogrithm for training the simple neural network
i = 0
while i < 100000: #number of iterations
    i += 1
    output = sigmoid(np.dot(X, W)) #The output from the neural network
    error = Y - output #The error by comparing the output with the expected output Y in our case
    '''The reason for multiplying the error by the derivative of the sigmoid function is to implement the gradient descent algorithm, 
        which is used to optimize the weights of the network.
      The derivative indicates the direction and rate of change of the error with respect to the weights, 
      so it's used to adjust the weights in the direction that most decreases the error.'''
    delta = error * sigmoid(output, True) #The delta value for updating the weights
    W = W + np.dot(X.T, delta)  #Updating the weights


print("Weights after training:")
print(W)

print("Output after training:")
print(output)

Weights after training
[[13.11370854]
 [-0.20370782]
 [-6.35334792]]
Output after training
[[0.00173789]
 [0.00141805]
 [0.99884253]
 [0.99858138]]


In [42]:
#Predicting the class of this observation [1, 0, 0] using the neural network after training (with the updated weights)
print("Prediction for [1, 0, 0]:")
print(sigmoid(np.dot(np.array([1, 0, 0]), W)))

Prediction for [1, 0, 0]:
[0.99999798]
